### ISSUE TITLE
Vocab RPG: Focus input on game start

### ISSUE THREAD

**Issue by earthiverse** [earthiverse/altivities#13]

**Comment by earthiverse** [comment]
Fixed in e4422a92f6376d5f2f5c39051f1d5d51af4f1804.

**Comment by scratix2023** [comment]
I really like this game and I think it will really help my students to study English. I can help providing a lot of vocabularies from Japanese to English using Sunshine textbooks but I don't know how to provide it to you. I hope this message reach you. Thank you!
