### ISSUE TITLE
を　ヲ Missing from Kana Race! :)

### ISSUE THREAD

**Issue by BrightMatt01** [earthiverse/altivities#25]
Hello,

I got my students to play Kana Race recently during break time and they noticed that を　ヲ that is supposed to come after わ　and before ん　is missing from the game itself.
https://www.busuu.com/user/pages/japanese/alphabet/hiragana/_02-text-1/learn-hiragana-chart-busuu.jpg?widthh=100%25class%3Dleft

I found files for を within the images and I'm no expert on this but I think it's simply a coding problem. I saw that script.ts also doesn't have them on the list so it has to be that.
class KanaRace {
    static KatakanaLetters = [..."アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワン"]
    static HiraganaLetters = [..."あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわん"]

Thank you for creating these amazing games!

**Comment by earthiverse** [comment]
Yeah, that's exactly what happened, I forgot to add を and ヲ to those two arrays.
Fixed in e1ea3e9d948a75ea910a4460bc0aeb9910a66012, thanks :)

**Comment by BrightMatt01** [comment]
That was fast, can't wait to let my students play it again next time! Thank you so much!!
